
site_name: Documentación cuadratura gaussiana

nav:
  - Inicio: index.md
  - Explicación: explanation.md
  - Tutorial: tutorials.md
  - Referencia: reference.md

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme: 
  name: material
